using System.Collections.Generic;

namespace SubtitleDb.Core
{
    /// <summary>
    /// The tables, generated from plugins/python/subtitledb/languages.py so the two
    /// cannot drift. Edit that file, then rerun plugins/dotnet/tools/gen-languages.py.
    /// </summary>
    internal static partial class LanguageTables
    {
        /// <summary>ISO639-1, plus the four OpenSubtitles codes, to display name.</summary>
        internal static readonly Dictionary<string, string> Names = new Dictionary<string, string>
        {
            { "pb", "Portuguese (Brazil)" },
            { "ze", "Chinese (bilingual)" },
            { "zt", "Chinese (traditional)" },
            { "pm", "Portuguese (Mozambique)" },
            { "ar", "Arabic" },
            { "bg", "Bulgarian" },
            { "bn", "Bengali" },
            { "bs", "Bosnian" },
            { "ca", "Catalan" },
            { "cs", "Czech" },
            { "da", "Danish" },
            { "de", "German" },
            { "el", "Greek" },
            { "en", "English" },
            { "eo", "Esperanto" },
            { "es", "Spanish" },
            { "et", "Estonian" },
            { "eu", "Basque" },
            { "fa", "Persian" },
            { "fi", "Finnish" },
            { "fr", "French" },
            { "gl", "Galician" },
            { "he", "Hebrew" },
            { "hi", "Hindi" },
            { "hr", "Croatian" },
            { "hu", "Hungarian" },
            { "hy", "Armenian" },
            { "id", "Indonesian" },
            { "is", "Icelandic" },
            { "it", "Italian" },
            { "ja", "Japanese" },
            { "ka", "Georgian" },
            { "kk", "Kazakh" },
            { "km", "Khmer" },
            { "ko", "Korean" },
            { "ku", "Kurdish" },
            { "lt", "Lithuanian" },
            { "lv", "Latvian" },
            { "mk", "Macedonian" },
            { "ml", "Malayalam" },
            { "mn", "Mongolian" },
            { "ms", "Malay" },
            { "my", "Burmese" },
            { "nl", "Dutch" },
            { "no", "Norwegian" },
            { "oc", "Occitan" },
            { "pl", "Polish" },
            { "pt", "Portuguese" },
            { "ro", "Romanian" },
            { "ru", "Russian" },
            { "si", "Sinhala" },
            { "sk", "Slovak" },
            { "sl", "Slovenian" },
            { "sq", "Albanian" },
            { "sr", "Serbian" },
            { "sv", "Swedish" },
            { "sw", "Swahili" },
            { "ta", "Tamil" },
            { "te", "Telugu" },
            { "th", "Thai" },
            { "tl", "Tagalog" },
            { "tr", "Turkish" },
            { "tt", "Tatar" },
            { "uk", "Ukrainian" },
            { "ur", "Urdu" },
            { "uz", "Uzbek" },
            { "vi", "Vietnamese" },
            { "zh", "Chinese" },
        };

        /// <summary>Three-letter forms. Both /T and /B: Jellyfin sends deu, Emby sends ger.</summary>
        internal static readonly Dictionary<string, string> Alpha3 = new Dictionary<string, string>
        {
            { "ara", "ar" },
            { "bul", "bg" },
            { "ben", "bn" },
            { "bos", "bs" },
            { "cat", "ca" },
            { "ces", "cs" },
            { "cze", "cs" },
            { "dan", "da" },
            { "deu", "de" },
            { "ger", "de" },
            { "ell", "el" },
            { "gre", "el" },
            { "eng", "en" },
            { "epo", "eo" },
            { "spa", "es" },
            { "est", "et" },
            { "eus", "eu" },
            { "baq", "eu" },
            { "fas", "fa" },
            { "per", "fa" },
            { "fin", "fi" },
            { "fra", "fr" },
            { "fre", "fr" },
            { "glg", "gl" },
            { "heb", "he" },
            { "hin", "hi" },
            { "hrv", "hr" },
            { "hun", "hu" },
            { "hye", "hy" },
            { "arm", "hy" },
            { "ind", "id" },
            { "isl", "is" },
            { "ice", "is" },
            { "ita", "it" },
            { "jpn", "ja" },
            { "kat", "ka" },
            { "geo", "ka" },
            { "kaz", "kk" },
            { "khm", "km" },
            { "kor", "ko" },
            { "kur", "ku" },
            { "lit", "lt" },
            { "lav", "lv" },
            { "mkd", "mk" },
            { "mac", "mk" },
            { "mal", "ml" },
            { "mon", "mn" },
            { "msa", "ms" },
            { "may", "ms" },
            { "mya", "my" },
            { "bur", "my" },
            { "nld", "nl" },
            { "dut", "nl" },
            { "nor", "no" },
            { "nob", "no" },
            { "nno", "no" },
            { "oci", "oc" },
            { "pol", "pl" },
            { "por", "pt" },
            { "pob", "pb" },
            { "ron", "ro" },
            { "rum", "ro" },
            { "rus", "ru" },
            { "sin", "si" },
            { "slk", "sk" },
            { "slo", "sk" },
            { "slv", "sl" },
            { "sqi", "sq" },
            { "alb", "sq" },
            { "srp", "sr" },
            { "swe", "sv" },
            { "swa", "sw" },
            { "tam", "ta" },
            { "tel", "te" },
            { "tha", "th" },
            { "tgl", "tl" },
            { "tur", "tr" },
            { "tat", "tt" },
            { "ukr", "uk" },
            { "urd", "ur" },
            { "uzb", "uz" },
            { "vie", "vi" },
            { "zho", "zh" },
            { "chi", "zh" },
        };

        /// <summary>Legacy codes, regional tags, and the names people write by hand.</summary>
        internal static readonly Dictionary<string, string> Aliases = new Dictionary<string, string>
        {
            { "iw", "he" },
            { "in", "id" },
            { "ji", "yi" },
            { "nb", "no" },
            { "nn", "no" },
            { "pt-br", "pb" },
            { "pt-pt", "pt" },
            { "por-br", "pb" },
            { "zh-hant", "zt" },
            { "zh-tw", "zt" },
            { "zh-hk", "zt" },
            { "zh-hans", "zh" },
            { "zh-cn", "zh" },
            { "sr-latn", "sr" },
            { "sr-cyrl", "sr" },
            { "es-419", "es" },
            { "es-mx", "es" },
            { "en-us", "en" },
            { "en-gb", "en" },
            { "brazilian portuguese", "pb" },
            { "portuguese brazilian", "pb" },
            { "simplified chinese", "zh" },
            { "traditional chinese", "zt" },
            { "chinese bilingual", "ze" },
            { "farsi", "fa" },
            { "castilian", "es" },
            { "flemish", "nl" },
            { "greek modern", "el" },
            { "serbo croatian", "sr" },
        };
    }
}
